version: '3.8'

services:

  db:
      container_name: pg_container
      image: postgres:14-alpine
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: test_db
      ports:
        - "5432:5432"
